---
- name: Install MS SQL Server
  hosts: "{{ hostlist | default('all') }}"
  vars:
    sqlsvr_iso_folder: C:\Users\Administrator\Downloads\
    sqlsvr_iso_name: SQLServer2019-x64-ENU.iso
    sqlsvr_configfile: "~/Documents/Downloads/MS-SQL-Server/ConfigurationFile.ini"
    sqlsvr_configfile_folder: C:\Users\Administrator\Downloads\
    sqlsvr_configfile_name: ConfigurationFile.ini
    sqlsvr_service: MSSQLSERVER
  tasks:

    - name: Create configuration file from template
      ansible.windows.win_template:
        dest: "{{ sqlsvr_configfile_folder }}{{ sqlsvr_configfile_name }}"
        newline_sequence: \r
        src: ConfigurationFile.ini.j2

    - name: Ensure MS SQL Server ISO is mounted
      community.windows.win_disk_image:
        image_path: "{{ sqlsvr_iso_folder }}{{ sqlsvr_iso_name }}"
        state: present
      register: disk_image_out

    - name: Run installer from mounted ISO
      ansible.windows.win_package:
        arguments:
          - "/ConfigurationFile={{ sqlsvr_configfile_folder }}{{ sqlsvr_configfile_name }}"
        creates_service: "{{ sqlsvr_service }}"
        path: '{{ disk_image_out.mount_paths[0] }}\setup.exe'
        state: present
      register: installer_out

    - name: Print all output
      debug:
        var: installer_out

    - name: Print if reboot required
      debug:
        msg: "Reboot required"
      when: installer_out.reboot_required

    - name: Unmount ISO
      community.windows.win_disk_image:
        image_path: "{{ sqlsvr_iso_folder }}{{ sqlsvr_iso_name }}"
        state: absent
